coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
        informational: true
    patch:
      default:
        informational: true

github_checks:
    annotations: false
