// This file was generated by liblab | https://liblab.com/

using Example;
using JsonApiDotNetCoreClientExample;
using JsonApiDotNetCoreClientExample.Config;
using Environment = JsonApiDotNetCoreClientExample.Http.Environment;

var config = new JsonApiDotNetCoreClientExampleConfig
{
    Environment = Environment.Default,
    AccessToken = "YOUR_ACCESS_TOKEN"
};

var client = new JsonApiDotNetCoreClientExampleClient(config);

var response = await client.People.GetPersonCollectionAsync();

// Commented out because it does not work due to broken inheritance.
//PeopleMessageFormatter.PrintPeople(response);

Console.WriteLine(response);
