// <auto-generated/>
#nullable enable
#pragma warning disable CS8625
using System.Runtime.Serialization;
using System;
namespace OpenApiKiotaEndToEndTests.ResourceInheritance.SubsetOfVarious.GeneratedCode.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RoadResourceType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "cyclePaths")]
        #pragma warning disable CS1591
        CyclePaths,
        #pragma warning restore CS1591
        [EnumMember(Value = "roads")]
        #pragma warning disable CS1591
        Roads,
        #pragma warning restore CS1591
    }
}
