// <auto-generated/>
#nullable enable
#pragma warning disable CS8625
using System.Runtime.Serialization;
using System;
namespace OpenApiKiotaEndToEndTests.QueryStrings.GeneratedCode.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum NodeResourceType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "nodes")]
        #pragma warning disable CS1591
        Nodes,
        #pragma warning restore CS1591
    }
}

