// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions.Store;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace OpenApiNSwagEndToEndTests.QueryStrings.GeneratedCode.Models {
    public class NodeRelationshipsInPatchRequest : IBackedModel, IParsable {
        /// <summary>Stores model information.</summary>
        public IBackingStore BackingStore { get; private set; }
        /// <summary>The children property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ToManyNodeInRequest? Children {
            get { return BackingStore?.Get<ToManyNodeInRequest?>("children"); }
            set { BackingStore?.Set("children", value); }
        }
#nullable restore
#else
        public ToManyNodeInRequest Children {
            get { return BackingStore?.Get<ToManyNodeInRequest>("children"); }
            set { BackingStore?.Set("children", value); }
        }
#endif
        /// <summary>The parent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public NullableToOneNodeInRequest? Parent {
            get { return BackingStore?.Get<NullableToOneNodeInRequest?>("parent"); }
            set { BackingStore?.Set("parent", value); }
        }
#nullable restore
#else
        public NullableToOneNodeInRequest Parent {
            get { return BackingStore?.Get<NullableToOneNodeInRequest>("parent"); }
            set { BackingStore?.Set("parent", value); }
        }
#endif
        /// <summary>The values property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ToManyNameValuePairInRequest? Values {
            get { return BackingStore?.Get<ToManyNameValuePairInRequest?>("values"); }
            set { BackingStore?.Set("values", value); }
        }
#nullable restore
#else
        public ToManyNameValuePairInRequest Values {
            get { return BackingStore?.Get<ToManyNameValuePairInRequest>("values"); }
            set { BackingStore?.Set("values", value); }
        }
#endif
        /// <summary>
        /// Instantiates a new nodeRelationshipsInPatchRequest and sets the default values.
        /// </summary>
        public NodeRelationshipsInPatchRequest() {
            BackingStore = BackingStoreFactorySingleton.Instance.CreateBackingStore();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static NodeRelationshipsInPatchRequest CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new NodeRelationshipsInPatchRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"children", n => { Children = n.GetObjectValue<ToManyNodeInRequest>(ToManyNodeInRequest.CreateFromDiscriminatorValue); } },
                {"parent", n => { Parent = n.GetObjectValue<NullableToOneNodeInRequest>(NullableToOneNodeInRequest.CreateFromDiscriminatorValue); } },
                {"values", n => { Values = n.GetObjectValue<ToManyNameValuePairInRequest>(ToManyNameValuePairInRequest.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<ToManyNodeInRequest>("children", Children);
            writer.WriteObjectValue<NullableToOneNodeInRequest>("parent", Parent);
            writer.WriteObjectValue<ToManyNameValuePairInRequest>("values", Values);
        }
    }
}
