// <auto-generated/>
#nullable enable
#pragma warning disable CS8625
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace OpenApiKiotaEndToEndTests.CustomRoutes.GeneratedCode.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RelationshipsInCreateElectionRequest : global::OpenApiKiotaEndToEndTests.CustomRoutes.GeneratedCode.Models.RelationshipsInCreateRequest, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The contenders property</summary>
        public global::OpenApiKiotaEndToEndTests.CustomRoutes.GeneratedCode.Models.ToManyCandidateInRequest? Contenders
        {
            get { return BackingStore?.Get<global::OpenApiKiotaEndToEndTests.CustomRoutes.GeneratedCode.Models.ToManyCandidateInRequest?>("contenders"); }
            set { BackingStore?.Set("contenders", value); }
        }

        /// <summary>The votes property</summary>
        public global::OpenApiKiotaEndToEndTests.CustomRoutes.GeneratedCode.Models.ToManyBallotInRequest? Votes
        {
            get { return BackingStore?.Get<global::OpenApiKiotaEndToEndTests.CustomRoutes.GeneratedCode.Models.ToManyBallotInRequest?>("votes"); }
            set { BackingStore?.Set("votes", value); }
        }

        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OpenApiKiotaEndToEndTests.CustomRoutes.GeneratedCode.Models.RelationshipsInCreateElectionRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::OpenApiKiotaEndToEndTests.CustomRoutes.GeneratedCode.Models.RelationshipsInCreateElectionRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::OpenApiKiotaEndToEndTests.CustomRoutes.GeneratedCode.Models.RelationshipsInCreateElectionRequest();
        }

        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "contenders", n => { Contenders = n.GetObjectValue<global::OpenApiKiotaEndToEndTests.CustomRoutes.GeneratedCode.Models.ToManyCandidateInRequest>(global::OpenApiKiotaEndToEndTests.CustomRoutes.GeneratedCode.Models.ToManyCandidateInRequest.CreateFromDiscriminatorValue); } },
                { "votes", n => { Votes = n.GetObjectValue<global::OpenApiKiotaEndToEndTests.CustomRoutes.GeneratedCode.Models.ToManyBallotInRequest>(global::OpenApiKiotaEndToEndTests.CustomRoutes.GeneratedCode.Models.ToManyBallotInRequest.CreateFromDiscriminatorValue); } },
            };
        }

        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<global::OpenApiKiotaEndToEndTests.CustomRoutes.GeneratedCode.Models.ToManyCandidateInRequest>("contenders", Contenders);
            writer.WriteObjectValue<global::OpenApiKiotaEndToEndTests.CustomRoutes.GeneratedCode.Models.ToManyBallotInRequest>("votes", Votes);
        }
    }
}
#pragma warning restore CS0618
