// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using OpenApiKiotaEndToEndTests.AtomicOperations.GeneratedCode.Enrollments.Item.Relationships.Course;
using OpenApiKiotaEndToEndTests.AtomicOperations.GeneratedCode.Enrollments.Item.Relationships.Student;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace OpenApiKiotaEndToEndTests.AtomicOperations.GeneratedCode.Enrollments.Item.Relationships
{
    /// <summary>
    /// Builds and executes requests for operations under \enrollments\{id}\relationships
    /// </summary>
    public class RelationshipsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The course property</summary>
        public OpenApiKiotaEndToEndTests.AtomicOperations.GeneratedCode.Enrollments.Item.Relationships.Course.CourseRequestBuilder Course
        {
            get => new OpenApiKiotaEndToEndTests.AtomicOperations.GeneratedCode.Enrollments.Item.Relationships.Course.CourseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The student property</summary>
        public OpenApiKiotaEndToEndTests.AtomicOperations.GeneratedCode.Enrollments.Item.Relationships.Student.StudentRequestBuilder Student
        {
            get => new OpenApiKiotaEndToEndTests.AtomicOperations.GeneratedCode.Enrollments.Item.Relationships.Student.StudentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="OpenApiKiotaEndToEndTests.AtomicOperations.GeneratedCode.Enrollments.Item.Relationships.RelationshipsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RelationshipsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enrollments/{id}/relationships", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="OpenApiKiotaEndToEndTests.AtomicOperations.GeneratedCode.Enrollments.Item.Relationships.RelationshipsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RelationshipsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enrollments/{id}/relationships", rawUrl)
        {
        }
    }
}
