// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OpenApiKiotaEndToEndTests.ClientIdGenerationModes.GeneratedCode.Models
{
    #pragma warning disable CS1591
    public enum GameResourceType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "games")]
        #pragma warning disable CS1591
        Games,
        #pragma warning restore CS1591
    }
}
