// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OpenApiKiotaEndToEndTests.ClientIdGenerationModes.GeneratedCode.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum PlayerResourceType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "players")]
        #pragma warning disable CS1591
        Players,
        #pragma warning restore CS1591
    }
}
