// <auto-generated/>
#nullable enable
#pragma warning disable CS8625
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace OpenApiKiotaEndToEndTests.MixedControllers.GeneratedCode.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AttributesInCreateCupOfCoffeeRequest : global::OpenApiKiotaEndToEndTests.MixedControllers.GeneratedCode.Models.AttributesInCreateRequest, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The hasMilk property</summary>
        public bool? HasMilk
        {
            get { return BackingStore?.Get<bool?>("hasMilk"); }
            set { BackingStore?.Set("hasMilk", value); }
        }

        /// <summary>The hasSugar property</summary>
        public bool? HasSugar
        {
            get { return BackingStore?.Get<bool?>("hasSugar"); }
            set { BackingStore?.Set("hasSugar", value); }
        }

        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OpenApiKiotaEndToEndTests.MixedControllers.GeneratedCode.Models.AttributesInCreateCupOfCoffeeRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::OpenApiKiotaEndToEndTests.MixedControllers.GeneratedCode.Models.AttributesInCreateCupOfCoffeeRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::OpenApiKiotaEndToEndTests.MixedControllers.GeneratedCode.Models.AttributesInCreateCupOfCoffeeRequest();
        }

        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "hasMilk", n => { HasMilk = n.GetBoolValue(); } },
                { "hasSugar", n => { HasSugar = n.GetBoolValue(); } },
            };
        }

        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteBoolValue("hasMilk", HasMilk);
            writer.WriteBoolValue("hasSugar", HasSugar);
        }
    }
}
#pragma warning restore CS0618
