// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OpenApiNSwagEndToEndTests.Headers.GeneratedCode.Models {
    public enum CountryResourceType {
        [EnumMember(Value = "countries")]
        Countries,
    }
}
