// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace JsonApiDotNetCoreClientExample.Models;

public record ResourceIdentifierTopLevelLinks(
    [property:
        JsonPropertyName("self"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Self = null,
    [property:
        JsonPropertyName("related"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Related = null,
    [property:
        JsonPropertyName("describedby"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Describedby = null
);
