// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using JsonApiDotNetCoreClientExample.Json;

namespace JsonApiDotNetCoreClientExample.Models;

public record TodoItemPriority : ValueEnum<string>
{
    internal TodoItemPriority(string value)
        : base(value) { }

    public TodoItemPriority()
        : base("High") { }

    public static TodoItemPriority High = new("High");
    public static TodoItemPriority Medium = new("Medium");
    public static TodoItemPriority Low = new("Low");
}
