// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions.Store;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace OpenApiKiotaEndToEndTests.RestrictedControllers.GeneratedCode.Models {
    #pragma warning disable CS1591
    public class DataInCreateWriteOnlyChannelRequest : IBackedModel, IParsable 
    #pragma warning restore CS1591
    {
        /// <summary>The attributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public AttributesInCreateWriteOnlyChannelRequest? Attributes {
            get { return BackingStore?.Get<AttributesInCreateWriteOnlyChannelRequest?>("attributes"); }
            set { BackingStore?.Set("attributes", value); }
        }
#nullable restore
#else
        public AttributesInCreateWriteOnlyChannelRequest Attributes {
            get { return BackingStore?.Get<AttributesInCreateWriteOnlyChannelRequest>("attributes"); }
            set { BackingStore?.Set("attributes", value); }
        }
#endif
        /// <summary>Stores model information.</summary>
        public IBackingStore BackingStore { get; private set; }
        /// <summary>The relationships property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RelationshipsInCreateWriteOnlyChannelRequest? Relationships {
            get { return BackingStore?.Get<RelationshipsInCreateWriteOnlyChannelRequest?>("relationships"); }
            set { BackingStore?.Set("relationships", value); }
        }
#nullable restore
#else
        public RelationshipsInCreateWriteOnlyChannelRequest Relationships {
            get { return BackingStore?.Get<RelationshipsInCreateWriteOnlyChannelRequest>("relationships"); }
            set { BackingStore?.Set("relationships", value); }
        }
#endif
        /// <summary>The type property</summary>
        public WriteOnlyChannelResourceType? Type {
            get { return BackingStore?.Get<WriteOnlyChannelResourceType?>("type"); }
            set { BackingStore?.Set("type", value); }
        }
        /// <summary>
        /// Instantiates a new <see cref="DataInCreateWriteOnlyChannelRequest"/> and sets the default values.
        /// </summary>
        public DataInCreateWriteOnlyChannelRequest()
        {
            BackingStore = BackingStoreFactorySingleton.Instance.CreateBackingStore();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="DataInCreateWriteOnlyChannelRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static DataInCreateWriteOnlyChannelRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new DataInCreateWriteOnlyChannelRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"attributes", n => { Attributes = n.GetObjectValue<AttributesInCreateWriteOnlyChannelRequest>(AttributesInCreateWriteOnlyChannelRequest.CreateFromDiscriminatorValue); } },
                {"relationships", n => { Relationships = n.GetObjectValue<RelationshipsInCreateWriteOnlyChannelRequest>(RelationshipsInCreateWriteOnlyChannelRequest.CreateFromDiscriminatorValue); } },
                {"type", n => { Type = n.GetEnumValue<WriteOnlyChannelResourceType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<AttributesInCreateWriteOnlyChannelRequest>("attributes", Attributes);
            writer.WriteObjectValue<RelationshipsInCreateWriteOnlyChannelRequest>("relationships", Relationships);
            writer.WriteEnumValue<WriteOnlyChannelResourceType>("type", Type);
        }
    }
}
