// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions.Store;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace OpenApiKiotaEndToEndTests.RestrictedControllers.GeneratedCode.Models {
    public class WriteOnlyChannelDataInPostRequest : IBackedModel, IParsable {
        /// <summary>The attributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public WriteOnlyChannelAttributesInPostRequest? Attributes {
            get { return BackingStore?.Get<WriteOnlyChannelAttributesInPostRequest?>("attributes"); }
            set { BackingStore?.Set("attributes", value); }
        }
#nullable restore
#else
        public WriteOnlyChannelAttributesInPostRequest Attributes {
            get { return BackingStore?.Get<WriteOnlyChannelAttributesInPostRequest>("attributes"); }
            set { BackingStore?.Set("attributes", value); }
        }
#endif
        /// <summary>Stores model information.</summary>
        public IBackingStore BackingStore { get; private set; }
        /// <summary>The relationships property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public WriteOnlyChannelRelationshipsInPostRequest? Relationships {
            get { return BackingStore?.Get<WriteOnlyChannelRelationshipsInPostRequest?>("relationships"); }
            set { BackingStore?.Set("relationships", value); }
        }
#nullable restore
#else
        public WriteOnlyChannelRelationshipsInPostRequest Relationships {
            get { return BackingStore?.Get<WriteOnlyChannelRelationshipsInPostRequest>("relationships"); }
            set { BackingStore?.Set("relationships", value); }
        }
#endif
        /// <summary>The type property</summary>
        public WriteOnlyChannelResourceType? Type {
            get { return BackingStore?.Get<WriteOnlyChannelResourceType?>("type"); }
            set { BackingStore?.Set("type", value); }
        }
        /// <summary>
        /// Instantiates a new writeOnlyChannelDataInPostRequest and sets the default values.
        /// </summary>
        public WriteOnlyChannelDataInPostRequest() {
            BackingStore = BackingStoreFactorySingleton.Instance.CreateBackingStore();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static WriteOnlyChannelDataInPostRequest CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new WriteOnlyChannelDataInPostRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"attributes", n => { Attributes = n.GetObjectValue<WriteOnlyChannelAttributesInPostRequest>(WriteOnlyChannelAttributesInPostRequest.CreateFromDiscriminatorValue); } },
                {"relationships", n => { Relationships = n.GetObjectValue<WriteOnlyChannelRelationshipsInPostRequest>(WriteOnlyChannelRelationshipsInPostRequest.CreateFromDiscriminatorValue); } },
                {"type", n => { Type = n.GetEnumValue<WriteOnlyChannelResourceType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<WriteOnlyChannelAttributesInPostRequest>("attributes", Attributes);
            writer.WriteObjectValue<WriteOnlyChannelRelationshipsInPostRequest>("relationships", Relationships);
            writer.WriteEnumValue<WriteOnlyChannelResourceType>("type", Type);
        }
    }
}
