// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OpenApiKiotaEndToEndTests.RestrictedControllers.GeneratedCode.Models {
    public enum WriteOnlyChannelResourceType {
        [EnumMember(Value = "writeOnlyChannels")]
        WriteOnlyChannels,
    }
}
