// <auto-generated/>
#nullable enable
#pragma warning disable CS8625
using System.Runtime.Serialization;
using System;
namespace OpenApiKiotaEndToEndTests.IdObfuscation.GeneratedCode.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BankAccountResourceType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "bankAccounts")]
        #pragma warning disable CS1591
        BankAccounts,
        #pragma warning restore CS1591
    }
}
