// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OpenApiKiotaEndToEndTests.AtomicOperations.GeneratedCode.Models
{
    #pragma warning disable CS1591
    public enum EnrollmentStudentRelationshipName
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "student")]
        #pragma warning disable CS1591
        Student,
        #pragma warning restore CS1591
    }
}
