// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OpenApiKiotaEndToEndTests.AtomicOperations.GeneratedCode.Models
{
    #pragma warning disable CS1591
    public enum RemoveOperationCode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "remove")]
        #pragma warning disable CS1591
        Remove,
        #pragma warning restore CS1591
    }
}
