// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OpenApiKiotaClientExample.GeneratedCode.Models {
    #pragma warning disable CS1591
    public enum TagResourceType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "tags")]
        #pragma warning disable CS1591
        Tags,
        #pragma warning restore CS1591
    }
}
