// <auto-generated/>
#nullable enable
#pragma warning disable CS8625
using System.Runtime.Serialization;
using System;
namespace OpenApiKiotaEndToEndTests.ResourceInheritance.OnlyRelationships.GeneratedCode.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RoomResidenceRelationshipName
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "residence")]
        #pragma warning disable CS1591
        Residence,
        #pragma warning restore CS1591
    }
}
