// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions.Store;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace OpenApiKiotaEndToEndTests.Links.GeneratedCode.Models {
    public class VacationRelationshipsInResponse : IBackedModel, IParsable {
        /// <summary>The accommodation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ToOneAccommodationInResponse? Accommodation {
            get { return BackingStore?.Get<ToOneAccommodationInResponse?>("accommodation"); }
            set { BackingStore?.Set("accommodation", value); }
        }
#nullable restore
#else
        public ToOneAccommodationInResponse Accommodation {
            get { return BackingStore?.Get<ToOneAccommodationInResponse>("accommodation"); }
            set { BackingStore?.Set("accommodation", value); }
        }
#endif
        /// <summary>Stores model information.</summary>
        public IBackingStore BackingStore { get; private set; }
        /// <summary>The excursions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ToManyExcursionInResponse? Excursions {
            get { return BackingStore?.Get<ToManyExcursionInResponse?>("excursions"); }
            set { BackingStore?.Set("excursions", value); }
        }
#nullable restore
#else
        public ToManyExcursionInResponse Excursions {
            get { return BackingStore?.Get<ToManyExcursionInResponse>("excursions"); }
            set { BackingStore?.Set("excursions", value); }
        }
#endif
        /// <summary>The transport property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public NullableToOneTransportInResponse? Transport {
            get { return BackingStore?.Get<NullableToOneTransportInResponse?>("transport"); }
            set { BackingStore?.Set("transport", value); }
        }
#nullable restore
#else
        public NullableToOneTransportInResponse Transport {
            get { return BackingStore?.Get<NullableToOneTransportInResponse>("transport"); }
            set { BackingStore?.Set("transport", value); }
        }
#endif
        /// <summary>
        /// Instantiates a new vacationRelationshipsInResponse and sets the default values.
        /// </summary>
        public VacationRelationshipsInResponse() {
            BackingStore = BackingStoreFactorySingleton.Instance.CreateBackingStore();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static VacationRelationshipsInResponse CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new VacationRelationshipsInResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"accommodation", n => { Accommodation = n.GetObjectValue<ToOneAccommodationInResponse>(ToOneAccommodationInResponse.CreateFromDiscriminatorValue); } },
                {"excursions", n => { Excursions = n.GetObjectValue<ToManyExcursionInResponse>(ToManyExcursionInResponse.CreateFromDiscriminatorValue); } },
                {"transport", n => { Transport = n.GetObjectValue<NullableToOneTransportInResponse>(NullableToOneTransportInResponse.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<ToOneAccommodationInResponse>("accommodation", Accommodation);
            writer.WriteObjectValue<ToManyExcursionInResponse>("excursions", Excursions);
            writer.WriteObjectValue<NullableToOneTransportInResponse>("transport", Transport);
        }
    }
}
