// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OpenApiKiotaEndToEndTests.Links.GeneratedCode.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum VacationResourceType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "vacations")]
        #pragma warning disable CS1591
        Vacations,
        #pragma warning restore CS1591
    }
}
